[package]
name = "neuralab"
description = "Official Neuralab Rust SDK"
license = "MIT"
version = "0.0.0"
edition = "2021"
homepage = "neuralab.dev"
documentation = "neuralab.dev/docs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
